repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    - id: flake8
      exclude: ^.*\b(migrations)\b.*$
      args: [--max-line-length=120, --max-complexity=19]


  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    - id: isort
      types: [python]