language: python
python:
  - "3.7.9"

services:
  - postgresql
  
  
before_script:
  - "flake8"
  - psql -c "CREATE USER testuser WITH PASSWORD 'test12345';" postgres
  - psql -c "alter user testuser with superuser;" postgres
  - psql -c 'create database testprojectdb with owner testuser;' postgres
  
install:
  - pip install -r requirements.txt


script:
  - coverage run -m pytest --pyargs cabins_test
  - coverage xml -i

after_success:
  - bash <(curl -s https://codecov.io/bash)
