apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}
  labels:
    app: {{ .Values.container.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.container.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}